/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inference.server;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGRPCBuilder() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.serverBuilder(), "app should have a GRPC builder");
    }
}
